const bones = [
  "Anococcygeal Ligament",
  "Arytenoid Cartilage",
  "Atlas Vertebra",
  "Auditory Tube",
  "Auricle",
  "Axis Vertebra",
  "Calcaneus",
  "Carpals",
  "Central Tendon",
  "Cervical Vertebrae",
  "Clavicle",
  "Clitoris",
  "Coccyx",
  "Corner of Mouth",
  "Cricoid Cartilage",
  "Cuboid",
  "Cuneiforms",
  "Distal Phalanges",
  "Distal Phalanx",
  "Epicranial Aponeurosis",
  "Extensor Expansions",
  "Eyelid",
  "Fascia Over Parotid Gland",
  "Fascia of Chest",
  "Femur",
  "Fibula",
  "First Rib",
  "Flexor Digitorum Longus",
  "Flexor Digitorum Profundus",
  "Frontal Bone",
  "Humerus",
  "Hyoid Bone",
  "Iliotibial Tract",
  "Ilium",
  "Inguinal Ligament",
  "Iris",
  "Ischium",
  "Knee Capsule",
  "Lens",
  "Linea Alba",
  "Lips",
  "Lumbar Vertebrae",
  "Malleus",
  "Mandible",
  "Mandibular Condyle",
  "Mastoid Process",
  "Maxilla",
  "Medial Cuneiform",
  "Metacarpal 1",
  "Metacarpal 5",
  "Metacarpals",
  "Metatarsal 1",
  "Metatarsal 5",
  "Metatarsals",
  "Middle Phalanges",
  "Nasal Bone",
  "Nasal Cartilage",
  "Nasal Septum",
  "Nose",
  "Occipital Bone",
  "Orbicularis Oris",
  "Orbital Floor",
  "Palatine Aponeurosis",
  "Palatine Bone",
  "Palmar Aponeurosis",
  "Penis",
  "Perineal Body",
  "Perineal Membrane",
  "Phalanges",
  "Pharyngeal Raphe",
  "Pharyngeal Wall",
  "Proximal Phalanges",
  "Proximal Phalanx",
  "Pterygoid Plate",
  "Pubis",
  "Radius",
  "Rib 1",
  "Ribs",
  "Sacrum",
  "Scapula",
  "Sclera",
  "Second Rib",
  "Skin Around the Eyes",
  "Skin of Chin",
  "Skin of Eyebrows",
  "Skin of Forehead",
  "Skin of Hand",
  "Skin of Lower Lip",
  "Skin of Upper Lip",
  "Spermatic Cord",
  "Sphenoid",
  "Sphenoid Bone",
  "Spinous Processes of Vertebrae",
  "Stapes",
  "Sternum",
  "Styloid Process",
  "Tarsals",
  "Temporal Bone",
  "Temporal Fascia",
  "Thoracic Vertebrae",
  "Thyroid Cartilage",
  "Tibia",
  "Tongue",
  "Ulna",
  "Upper Lip",
  "Urethra",
  "Uvula",
  "Vagina",
  "Vertebrae",
  "Zygomatic Arch",
  "Zygomatic Bone",
];
