const bones = {
  headAndNeck: [
    "Anococcygeal Ligament",
    "Arytenoid Cartilage",
    "Auditory Tube",
    "Auricle",
    "Corner of Mouth",
    "Cricoid Cartilage",
    "Eyelid",
    "Frontal Bone",
    "Hyoid Bone",
    "Iris",
    "Lens",
    "Lips",
    "Malleus",
    "Mandible",
    "Mandibular Condyle",
    "Mastoid Process",
    "Maxilla",
    "Nasal Bone",
    "Nasal Cartilage",
    "Nasal Septum",
    "Nose",
    "Occipital Bone",
    "Orbicularis Oris",
    "Orbital Floor",
    "Palatine Aponeurosis",
    "Palatine Bone",
    "Pharyngeal Raphe",
    "Pharyngeal Wall",
    "Pterygoid Plate",
    "Sclera",
    "Skin Around the Eyes",
    "Skin of Chin",
    "Skin of Eyebrows",
    "Skin of Forehead",
    "Skin of Lower Lip",
    "Skin of Upper Lip",
    "Sphenoid",
    "Sphenoid Bone",
    "Stapes",
    "Styloid Process",
    "Temporal Bone",
    "Temporal Fascia",
    "Thyroid Cartilage",
    "Tongue",
    "Upper Lip",
    "Uvula",
    "Zygomatic Arch",
    "Zygomatic Bone",
    "Epicranial Aponeurosis",
    "Fascia Over Parotid Gland",
  ],
  thorax: [
    "Clavicle",
    "First Rib",
    "Second Rib",
    "Rib 1",
    "Ribs",
    "Sternum",
    "Fascia of Chest",
    "Thoracic Vertebrae",
    "Central Tendon",
  ],
  abdomen: ["Linea Alba", "Inguinal Ligament"],
  pelvisAndPerineum: [
    "Clitoris",
    "Coccyx",
    "Ilium",
    "Ischium",
    "Pubis",
    "Sacrum",
    "Penis",
    "Perineal Body",
    "Perineal Membrane",
    "Spermatic Cord",
    "Urethra",
    "Vagina",
  ],
  upperLimb: [
    "Carpals",
    "Clavicle",
    "Extensor Expansions",
    "Flexor Digitorum Profundus",
    "Humerus",
    "Metacarpal 1",
    "Metacarpal 5",
    "Metacarpals",
    "Phalanges",
    "Proximal Phalanges",
    "Proximal Phalanx",
    "Middle Phalanges",
    "Distal Phalanges",
    "Distal Phalanx",
    "Radius",
    "Scapula",
    "Skin of Hand",
    "Ulna",
    "Palmar Aponeurosis",
  ],
  lowerLimb: [
    "Calcaneus",
    "Cuboid",
    "Cuneiforms",
    "Femur",
    "Fibula",
    "Flexor Digitorum Longus",
    "Iliotibial Tract",
    "Knee Capsule",
    "Metatarsal 1",
    "Metatarsal 5",
    "Metatarsals",
    "Phalanges",
    "Proximal Phalanges",
    "Proximal Phalanx",
    "Middle Phalanges",
    "Distal Phalanges",
    "Distal Phalanx",
    "Tibia",
    "Tarsals",
    "Medial Cuneiform",
  ],
  back: [
    "Atlas Vertebra",
    "Axis Vertebra",
    "Cervical Vertebrae",
    "Lumbar Vertebrae",
    "Thoracic Vertebrae",
    "Sacrum",
    "Coccyx",
    "Spinous Processes of Vertebrae",
    "Vertebrae",
  ],
};
